server:
  port: 9092
service:  
  register:
    center:
      ip: 127.0.0.1
      port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: http://${service.register.center.ip}:${service.register.center.port}/eureka/

spring:
  application: 
    name: smart-imate