db: 
  ip: 192.168.29.30
  port: 3306
  name: gmws_copy
  username: gmws
  password: gmws
  url: jdbc:mysql://${db.ip}:${db.port}/${db.name}?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true
#数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #username: dsol
    #password: Ev2ayJRneWdjW1UaYrMYpEWzd2tF3kgVYX269wwP/nXnhIHDG3fBkiIqF7IZ6o5FEPGUbwrq4Jxe5gUseHiq0Q==
    #url: jdbc:mysql://${db.ip}:${db.port}/${db.name}?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true
    druid:
      filter-class-names: stat
      filters: stat,config
      #初始化连接大小
      initial-size: 8
      #最小空闲连接数
      min-idle: 5
      #最大连接数
      max-active: 10
      #查询超时时间
      query-timeout: 6000
      #事务查询超时时间
      transaction-query-timeout: 6000
      #关闭空闲连接超时时间
      remove-abandoned-timeout: 1800
mybatis: 
  #config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml,classpath*:mapper/*.xml        