spring:
  application:
    name: gmws-zuul
server:
  port: 8040
#eureka server config
service:  
  register:
    center:
      ip: 127.0.0.1
      hostname: peer1
      port: 9081
#eureka client defined        
eureka:
  client:
    serviceUrl:
      defaultZone: http://${service.register.center.hostname}:${service.register.center.port}/eureka/
    registry-fetch-interval-seconds: 5 #拉取服务注册信息时间间隔,默认为30秒
  instance:
    prefer-ip-address: true  
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 5 #心跳时间,默认为30秒
    lease-expiration-duration-in-seconds: 10 #若eureka server在这时间内没收到心跳则移除该instance,默认为90秒
#配置zuul
zuul:
  routes:
    abc: 
      path: /smart-imate-proxy/**
      service-id: smart-imate
    disease: 
      path: /gmws-disease-proxy/**
      service-id: gmws-knowleadge-disease
